### DISCUSSION TITLE
using LADSPA plugins on banks

### DISCUSSION THREAD

**Discussion by arretxe** [GeekFunkLabs/fluidpatcher#114] [Q&A]
Hi all!
I am using fluidpatcher for live performing and I want to add some plugins to my sf2. I have tried setting the SC4 compressor but I cannot seem to make it work. I set the threshold, makeup gain and attack to the minimum and still it seems to sound exactly the same...
When loading the bank i don't see any error so first I thought it was understanding what I was setting, but then i set some fake port names and i don't get any errors, so right now I can't tell if I am setting it properly....

Any help would be really appreciated!

These is the plugin I am using:
analyseplugin /usr/lib/ladspa/sc4_1882.so

Plugin Name: "SC4"
Plugin Label: "sc4"
Plugin Unique ID: 1882
Maker: "Steve Harris <steve@plugin.org.uk>"
Copyright: "GPL"
Must Run Real-Time: No
Has activate() Function: No
Has deactivate() Function: No
Has run_adding() Function: Yes
Environment: Normal or Hard Real-Time
Ports:  "RMS/peak" input, control, 0 to 1, default 0
        "Attack time (ms)" input, control, 1.5 to 400, default 101.125
        "Release time (ms)" input, control, 2 to 800, default 401
        "Threshold level (dB)" input, control, -30 to 0, default 0
        "Ratio (1:n)" input, control, 1 to 20, default 1
        "Knee radius (dB)" input, control, 1 to 10, default 3.25
        "Makeup gain (dB)" input, control, 0 to 24, default 0
        "Amplitude (dB)" output, control, -40 to 12
        "Gain reduction (dB)" output, control, -24 to 0
        "Left input" input, audio
        "Right input" input, audio
        "Left output" output, audio
        "Right output" output, audio
        
And my files:      
fluidpatcherconf.yaml  

soundfontdir: /home/st/scripts/config/sf2
bankdir: /home/st/scripts/config/banks
mfilesdir: /home/st/scripts/config/midi
plugindir: /usr/lib/ladspa
currentbank: bank1.yaml
fluidsettings:
  audio.driver: alsa
  audio.realtime-prio: 99
  audio.alsa.device: hw:CODEC
  audio.period-size: 64
  audio.periods: 2
  midi.autoconnect: 1
  player.reset-synth: 0
  synth.audio-groups: 1
  synth.chorus.active: 0
  synth.reverb.active: 0
  synth.sample-rate: 48000
  synth.gain: 0.8
  synth.cpu-cores: 4
  synth.ladspa.active: 1
  synth.min-note-length: 0
  synth.polyphony: 32

bank1.yaml

patches:
  mysf: 
    1: my_sf.sf2:000:000
    ladspafx:
      compressor1:
        lib: sc4_1882.so
        audio: stereo
        group: 1
        vals: 
          Ratio: 20
          Threshold: -30
          Attack: 1.5
          Release: 800
          Makeup: 0

Related questions:
Can I set the plugin at the init section of the bank? I have tried it with no success...
Is there some kind of wet/dry setting that I am missing?
Since I am setting synth.audio-groups to 1 I guess the group setting of the plugin should also be set to 1 right?

**Comment by arretxe** [comment]
I have edited the __init__.py file to check for the port names and make sure they are correct, by adding these lines in the load_bank function within the for fx in zone.get...


                result = subprocess.run(['analyseplugin', str(fx['lib'])], capture_output=True, text=True)
                valid_ports = []
                for line in result.stdout.splitlines():
                    if 'input, control' in line:
                        port_name = line.split('"')[1]  # Extract port name
                        valid_ports.append(port_name)
                user_vals = fx.pars.get('vals', {});
                for port in user_vals.keys():
                    if not any(valid_port.startswith(port) for valid_port in valid_ports):
                        raise ValueError(f"Invalid port name: {port}. Must be one of {valid_ports}")

**Comment by arretxe** [comment]
I tried with jack instead of alsa and still the same behavior.

**Comment by albedozero** [comment]
Hey, sorry for the delayed response. You need to change the `audio: stereo` parameter to `audio: Left in, Right in, Left out, Right out`.

As explained in the [Plugins](https://geekfunklabs.github.io/fluidpatcher/ladspa_plugins/#usage) section of the docs, `audio: stereo` is an alias for `audio: Input L, Input R, Output L, Output R`, since the majority of LADSPA plugins I surveyed named their outputs this way. Steve Harris didn't, though - if you look at the last four lines of output from `analyseplugin` you can see they're named differently. If you run fluidpatcher from a command line with the wrong input/output port names you should see some errors like

```bash
fluidsynth: error: Port 'Input L' not found on effect 'compressor10'
fluidsynth: error: Port 'Output L' not found on effect 'compressor10'
fluidsynth: error: Port 'Input R' not found on effect 'compressor10'
fluidsynth: error: Port 'Output R' not found on effect 'compressor10'
fluidsynth: error: LADSPA check failed, unable to activate effects
```

which can hopefully give you a clue when this is happening.

**Reply by albedozero** [reply]
Here's a version of your bank that should work, with some added router rules so you can tweak the compressor effect.

```yaml
patches:
  withcomp:
    1: my_sf.sf2:000:000
    ladspafx:
      compressor1:
        lib: sc4_1882.so
        audio: Left in, Right in, Left out, Right out
        group: 1
        vals:
          Ratio: 20
          Threshold: -30
          Attack: 1.5
          Release: 800
          Makeup: 0
    router_rules:
    - {type: cc, par1: 30, par2: 0-127=1-20, ladspafx: compressor1, port: Ratio}
    - {type: cc, par1: 31, par2: 0-127=-30-0, ladspafx: compressor1, port: Threshold}
    - {type: cc, par1: 32, par2: 0-127=1.5-400, ladspafx: compressor1, port: Attack}
    - {type: cc, par1: 33, par2: 0-127=2-800, ladspafx: compressor1, port: Release}
  nocomp:
    1: my_sf.sf2:000:000
```
