### DISCUSSION TITLE
Testing tap tempo and external clock sync

### DISCUSSION THREAD

**Discussion by albedozero** [GeekFunkLabs/fluidpatcher#45] [Ideas]
Since the [v0.7.7 release](https://github.com/albedozero/fluidpatcher/releases/tag/v0.7.7), FluidPatcher recognizes some [system realtime messages](https://www.recordingblogs.com/wiki/midi-system-realtime-messages), specifically _MIDI clock, start, stop_, and _continue_. These can be used to trigger router rules that start/stop sequencers/players, and can also be used with the tempo sync feature to synchronize FluidPatcher with an external clock, say from a drum machine or external sequencer. For example:

```yaml
10: FluidR3_GM.sf2:128:000
sequencers:
  drums:
    notes: [note:10:36:100, note:10:0:0, note:10:38:100, note:10:0:0,
            note:10:36:100, note:10:36:100, note:10:38:100, note:10:0:0]
router_rules:
- {type: cc, par1: 21, par2: 127=-1, sequencer: drums}
- {type: cc, par1: 22, par2: 127=0, sequencer: drums}
- {type: cc, par1: 15, par2: 0-127=50-200, tempo: drums}
- {type: cc, par1: 24, par2: 127=1, sync: drums}
- {type: start, sequencer: drums}
- {type: stop, sequencer: drums}
- {type: clock, sync: drums}
```
