### DISCUSSION TITLE
Is it possible to remap velocity values in fluidpatcher?

### DISCUSSION THREAD

**Discussion by Syridian** [GeekFunkLabs/fluidpatcher#52] [Q&A] [answered]
Hi,

I am new to Midi so this might be a question that I'm just thinking about in the wrong way, but is it possible to change the velocity curve between the Midi input and the Syth?  Low velocities are extremely low on the keyboard I'm using and I can't seem to work out if that's the keyboard's fault or if there's a way of remapping the values between the keyboard and fluid patcher.

**Comment by albedozero** [comment, marked as answer]
You can use router rules to modify the velocity (`par2`) of note messages based on a range, like the example below. This isn't a curve exactly and requires some math and/or trial and error, but you can probably achieve something useful enough this way. Most MIDI keyboards I've used have some way to select the velocity curve if you dig through the manual - maybe yours got set to a really odd one?

```yaml
patches:
  Boost:
    2: FluidR3_GM.sf2:000:000
    router_rules:
    - {type: note, chan: 1=2, par2: 1-40*2+0}
    - {type: note, chan: 1=2, par2: 41-127*0.6+56}
```
![image](https://user-images.githubusercontent.com/16512151/178630499-632023ca-66da-4a02-b10b-d0b2da7e976d.png)
