### ISSUE TITLE
Question about routing

### ISSUE THREAD

**Issue by kentron** [GeekFunkLabs/fluidpatcher#44]
Hi Albedozero, how are you

Thank you for this wrapper, I'm currently adapting it for a performance with an early music ensemble. I intend to emulate pipe organ stops, but I wonder what it would be the best way to do so. I'm trying to avoid assigning volume = 0 for a particular channel. Instead, I would like to turn on/off a given program by routing/unrouting channel 1 to the channel assigned in the bank file for the preset. The behavior should be like turning on and off a particular preset. 
Is there a way to unroute a previously routed channel? Do I Need to extend fswrap.py to  add a function to wrap fluidsynth's api call 'delete_fluid_midi_router_rule'? In that case: how do I refer to the id of an existing rule?

Thank you very much for the advice

**Comment by albedozero** [comment]
Unfortunately the only way to remove a rule once it's added to the router is to clear all the rules and start again. As the [FluidSynth API states](https://www.fluidsynth.org/api/group__midi__router.html#gafa33ca65b0db6aaf16627c1972edaeb3), once you pass a rule to `fluid_midi_router_add_rule()` it should not be accessed again. This is because rules are stored in the router in a linked-list structure - removing a rule would break the link and probably cause a segfault. I think `delete_fluid_midi_router_rule()` is meant to be used on a rule you've created but not yet added to the router.

What's your reason for not wanting to use CC7=0 to mute particular channels? I know that this can cause unwanted behavior if you also use the volume slider on your keyboard to control the volume on all channels - those muted voices will pop back on if you move the slider. The workaround is to use CC11 to mute voices when needed as discussed in [FluidPatcher Lesson 4](https://youtu.be/K_TKv0kQubU). The sound volume is the _product_ of MIDI volume (CC7) and Expression (CC11), so an expression level of 0 is unaffected by changing the volume. This was designed into the MIDI specification for pretty much this exact reason. Here's an example bank file that would do something like you're suggesting:

```yaml
patches:
  Drawbars:
    1: organ/Oberheim OB-3.sf2:000:001
    2: organ/Oberheim OB-3.sf2:000:002
    3: organ/Oberheim OB-3.sf2:000:003
    router_rules:
    - {type: note, chan: 1=2-3}
    - {type: cc, chan: 1, par1: 13=11}
    - {type: cc, chan: 1=2, par1: 14=11}
    - {type: cc, chan: 1=3, par1: 15=11}
    - {type; cc, chan: 1=1-16, par1: 7}
```
